@url_dev=http://localhost:3000/api/v1/accounts
### signup
POST {{url_dev}}/signup
Content-Type: application/json

{
  "username": "toilahuong",
  "email": "toilahuong@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

### login
POST {{url_dev}}/login
Content-Type: application/json

{
  "account": "admin",
  "password": "123456"
}

### checklogin
GET {{url_dev}}/check-auth
X-Client-ID: 642fdcb4af2a0df12e662315
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDJmZGNiNGFmMmEwZGYxMmU2NjIzMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjgxNzY0NDU0LCJleHAiOjE2ODIzNjkyNTR9.ndmI3dVH8OmLvfHVv3MGWL5ozF2PA29DQ8W1_E8i08ygfb5gJxySr0OvYgIjRIFXlm2uoQUo971d-eD_I3Rn6CpwWgvVIae4fz03iYddHNgVyR6l9MPut2ni2WQ37bAYlZoUF_AL7MA8UukcXqjuS3VCs-QteD8hZjmOiB-znFMVCtbpu4qwxWG94DiqjohDU1ouBCGsXDWexce5p6B_IA9hHMCPD5CeNG68s4WCuLZzgNR0h61hHHoloJof3zTjuRw6hK3sJxVvjxRlnP7otQcSen1QOcJ_2aeAx6scxXDCqBT-Qi8iqeKiQSByejhlps-m-WP-9_GWErtCrQ4pWnE57kRcsRNU0cPUfUINsz_lwP3UAMjI2Ap42-jqEB17gAQJ3upT_KEzxxeulZy3Zx-yk-c8AKvbt2CO8-ayIDL1FKaOBjDwVbUJpPDtV6GnzI1bgqO1jkmFH6s5BdngbtyW1SIxH6A9zRL7bEhkol2cihif0uru2mAd_6gFQ53WZsOGA2PgMtwwk_6eNVBQxgy605I_9svqepN8Tr3s3TzP0Bmo2m3HrAO3bqn2onb4J_KdWPawW04EhVLn58Poe2kzcrt-r3B3U-_1NX4PbV8oxdGiQpnUSzghcYyH2BM69bfTNaym_8GjLNwmVg44M9s0c91pD1IPig0kQNwWahY

### logout
POST {{url_dev}}/logout
X-Client-ID: 642c40f32ee63685dba73c82
X-Device-ID: 642c40f42ee63685dba73c85
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJjNDBmMzJlZTYzNjg1ZGJhNzNjODIiLCJ1c2VybmFtZSI6IkY0RG5vRDRiWWwiLCJpYXQiOjE2ODA2MjE4MTIsImV4cCI6MTY4MDc5NDYxMn0.k5kDjb9Su2NLRAqaSTXBBPf61nFZabkE1vRHjdXgr1ScnnHGPG6XKrro60Y2E1P4p0ZPvMoxbgw4JUELqcAanDe23WHERWmrsLgkNCezKxSZ9N25BuMAngWMHJA8V_P8gTsZ2h_GhO0x7xWjGU3qHSy46WkBZRzyxIEbsB7fWyOjz30u4S3WBQFuXiz0MrYia0zQBt0Ugm_SXl_WOk9wrqs1jFvcRfyFXb8Q6np5CKVbfPEiAcVxVthUDmorNHFd8ZvUCYxMpSqSRNLQctp184T1ucHbrlIZZU7foiYFHs-IxvDxlSM_rE12dZv0C2bOcrgM_lPLH51c0owEwpx8-mLX4coiQi2MApfu5jOPR6KR3L6OdxVfbrjMIEnktA3_J_I1bzlryoPMacKvpKiwDp81pAKknSmb_e1UbGFwx2oFb23XqTdGgAEH3hnjWTsvgXfTyKwDlhA0W4qtt20bMx7yVwEMUDW5vLdImSWPabe-DVsz62AKDLBOqEDpdb-kFKpB2tn7nvFiZXuYIm7fDLuRfSzu9BX8xMJgWx4Ptp_7WrjPEIblmnSqZqGafqDqcWj1QlE1GfbiWalEWmHEXINl0GHfNz4mIh1tqIR-YrArUYC71faW3Z8XTVpZmwFvGaDMd6D6L4Q4o0dqIEBmm7h34iaH1xyW1mjR6fhNHvY

### refresh-token
POST {{url_dev}}/refresh-token
X-Client-ID: 642c40f32ee63685dba73c82
X-Device-ID: 642dac1bff055b16cb7964d7
Refresh-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJkYWMxYmZmMDU1YjE2Y2I3OTY0ZDQiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA3MTQ3NzksImV4cCI6MTY4MDcxNDgzOX0.xbQoXP3SFSaAd74N0D7gUcCFaGd5eQc2YgFw8XkQBO6SmSvpeFbO0Plzozy8muQZnpfzANo1LTxokI48e5cm_2i3v441uxiueqjvpVhhCkb9bVuUlPQTwNjYSNdXjc8PwVd42vbd_Hu0jNmY0felnwjzc1YyiS7BsPUJF0DIhtJE2vB2J4L645IrV1kh-vZ-Oe_28VSmqVn2blZRabpFm4RAkdXEfxOo3dJx7zrIJNsDGzXKeD33WFuK1YA3JyPX9IaW4k_py6EOtetZbmj2Sb6BYuUTMG-tgzMvEuv5Ui-XRxcE_KYogjUnRoJcWisAzkOF3fXyheHx4WnGrXI1Pf0H7-KYptOgbKvNR5KSdC2QREaIl0o_0o0LdTj1zf0WW_t12S2qu_f9c9wpi1Mn4-sEONN8IdANBAUysWcWb7m54EBu2aBKelwAXIzN39NIkOY33yDTmIEAC3JqnDft4tmogbCNLIiGCktu4slCQ2RTYDS3sIs0uIMbSplPhu9N7-zynSYWUUCQCBYO8wtxueDUCEErrFarsZ4kGTXN6ZXby24QTKj15YIn7f4vJgpWUO63lw8jWASmnzBFLad10FjlPnBcK77M0p4M_byLcaWzwdt6KcwOTCIw-YUAZjMYDZ2d3aK_NrcSjmkJN51GXXikB8i0YBLbhihKFyaYjPo

### change-password
PATCH {{url_dev}}/change-password
Content-Type: application/json
X-Client-ID: 642f100f1e6d40dc52e1caf5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmMTAwZjFlNmQ0MGRjNTJlMWNhZjUiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA4MDU5MDMsImV4cCI6MTY4MDgwOTUwM30.N9iyZ2l3srHEK_uoAbOZ-dtjjY9yyfPKaD2PTDiz8r81DBkiEpb7UINDuPrzifrQCdVyIfkLWz6Jf72g5PRZWrw9OEsg9um3l3RoSpVdnzWQmH7ALRSIeWcLoGxTA3vKg9GRRBlef0aZxelVygcJW1-ygwi-NhZLAN2eZlwv4_prnS_6dIix7YkDXAs5Nv1HU_c2vBhxpFU_l7VdablQ3sqgzBVw5uqMXI6wfNi-rZtI6GVTiXIfVHwkHTf0D5nH9wNgIH__4aKpyTYS4X6rQH3C9mwLnmbGi5TaHor7L46QEcccD8F8mI2EREbUYR7wiDD8fwqWO8hZ_jTyqOXU5m4Mn7540VGsmAlE-nx0I75wkxuVRui-wTH0zlh9dpJqqGMmt-Xqa-upOQI686-d39AlxLcnVOdmLWIBJCKoxTp9sQBaiZTMutJHIFnZ1KHjQjxEc0pjHMPsWxm3AmZ3GI__RzlTm38-QuPHD2sYfzzwzi8IC27ceeJxhBRlTCqs1xWR97HSr36NTM_rAL5sbh21K8kTWKodEADrESWwBtFAOvgx0l0dFkzH75a88mzlWNSWrKz8LG8EIrT4COwmohzRPOz6yvUZG3xPlir5lz3YWxHwmzdiP3AvdvDTaUYOHfQY-ZgtKoje147QSjCyF-sZrcfDiEtfmiZ6hfduu90

{
  "oldPassword": "123456",
  "newPassword": "1234567",
  "confirmPassword": "1234567"
}

### change-information
PATCH {{url_dev}}/change-information
Content-Type: application/json
X-Client-ID: 642f100f1e6d40dc52e1caf5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmMTAwZjFlNmQ0MGRjNTJlMWNhZjUiLCJ1c2VybmFtZSI6InRvaWxhaHVvbmciLCJpYXQiOjE2ODA4MDU5MDMsImV4cCI6MTY4MDgwOTUwM30.N9iyZ2l3srHEK_uoAbOZ-dtjjY9yyfPKaD2PTDiz8r81DBkiEpb7UINDuPrzifrQCdVyIfkLWz6Jf72g5PRZWrw9OEsg9um3l3RoSpVdnzWQmH7ALRSIeWcLoGxTA3vKg9GRRBlef0aZxelVygcJW1-ygwi-NhZLAN2eZlwv4_prnS_6dIix7YkDXAs5Nv1HU_c2vBhxpFU_l7VdablQ3sqgzBVw5uqMXI6wfNi-rZtI6GVTiXIfVHwkHTf0D5nH9wNgIH__4aKpyTYS4X6rQH3C9mwLnmbGi5TaHor7L46QEcccD8F8mI2EREbUYR7wiDD8fwqWO8hZ_jTyqOXU5m4Mn7540VGsmAlE-nx0I75wkxuVRui-wTH0zlh9dpJqqGMmt-Xqa-upOQI686-d39AlxLcnVOdmLWIBJCKoxTp9sQBaiZTMutJHIFnZ1KHjQjxEc0pjHMPsWxm3AmZ3GI__RzlTm38-QuPHD2sYfzzwzi8IC27ceeJxhBRlTCqs1xWR97HSr36NTM_rAL5sbh21K8kTWKodEADrESWwBtFAOvgx0l0dFkzH75a88mzlWNSWrKz8LG8EIrT4COwmohzRPOz6yvUZG3xPlir5lz3YWxHwmzdiP3AvdvDTaUYOHfQY-ZgtKoje147QSjCyF-sZrcfDiEtfmiZ6hfduu90

{
  "fullname": "Toi",
  "phoneNumber": "0357654619",
  "address": "Ha Noi"
}

### get list users
GET {{url_dev}}
Content-Type: application/json
X-Client-ID: 642fdcb4af2a0df12e662315
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NDJmZGNiNGFmMmEwZGYxMmU2NjIzMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjgyMzk2ODg1LCJleHAiOjE2ODMwMDE2ODV9.fW1-_I24R6IKymlGv4IEPM-Iun3dJZLcPLDjUIpFAT1N-9h-CQfnBXDG9THhIEiqwf2Q5tTZUTDeaqpx5t2Xx2mM7TY-yBDibnrmr0pJL8xIZQL8uLXckte9keezTUMNs-4e4hv7RLY1tJIwMeGiE7607a9vWeoLn5bvj9t1_oDDJrAWVIT974mAWGSSpz2KneRpXWN0PZI2Lct3I5A31hMoj59P_iBJfU4DwdiVJpf7a9FS67CbYMJiHd-eL2fVxVZOakRTKVOwgjWhlSC1Ybo7i8V-tskk3sxauf8QDJx9NTYwSWXvETuejpdvMA3ogm7-llAW4-TGyuET4wC6o7eRckHrIL71XpdS5ypJOo6N_WVC-TqhmRCjJTx_UOLSLsI_v-9LtUQIX-7_ca2EiewDFuOEkYQ3pePSPNjtLniblXmQnZV3EiIWrEn7fO69cfns5SnlsMo-4F1jVvVfHEOYBkKoT1KRIyjs1kBzCjLC5vAaprLL_JzyW4trkYa3LNULc2zn4bxRlafMtpVrqujJCgcWnCumw6LMd8r8pV4I2JyFyeFrqIm6xJiu9BdfMntergsyJd9cjaiisEyBQiBZPgw0KCLVXeHfN_TuUhiI0F_NB3PY0Km9ey-E0nxU1b6xblqrI1JGQmznWGhH-cL8vT9t_v0ctX8ADmypQgo